def patrones_ruler():
    return [
            {"label": "DIAG", "pattern": "Colección supurada sin especificar su localización."},
            {"label": "DIAG", "pattern": "inflamación en encía y/o tejidos circundantes, secundaría a patología dental"},
            {"label": "DIAG", "pattern": "Sospecha de agresión sexual y/o física, existan lesiones evidenteAumento de tamaño de ganglios linfáticos"},
            {"label": "DIAG", "pattern": "tumefacción ganglionar aguda con signos inflamatorios, con o sin fluctuación"},
            {"label": "DIAG", "pattern": "presencia de valores de hematacrito y hemoglobina por debajo de las cifras normales para la edad del paciente"},
            {"label": "DIAG", "pattern": "presenta alteración morfológica de los hematíes que pierden su forma y adoptan un aspecto semilunar"},
            {"label": "DIAG", "pattern": "presenta Edema angioneurótico de contacto inicial"},
            {"label": "DIAG", "pattern": "Presenta síntomas psíquicos y/o somáticos de ansiedad atribuidos a la presencia de temor o preocupación desligados de hechos o situaciones que los justifiquen"},
            {"label": "DIAG", "pattern": "presenta apendicitis por Inflamación apendicular sin perforacion"},
            {"label": "DIAG", "pattern": "dolor articular sin otros signos inflamatorios como artralgias"},
            {"label": "DIAG", "pattern": "Artritis inespecífica por Inflamación articular"},
            {"label": "DIAG", "pattern": "Artritis séptica por Inflamación articular de origen bacteriano"},
            {"label": "DIAG", "pattern": "sintomas respiratorios de asma atribuidos a broncoespasmo"},
            {"label": "DIAG", "pattern": "presenta ataxia por la alteracion de la coordinacion de los movimientosvoluntarios y del equilibrio"},
            {"label": "DIAG", "pattern": "presenta balanitis por la inflamacion del grande asociada al prepucio"},
            {"label": "DIAG", "pattern": "presencia de signos y sintomas respiratorios atribuidos a la inflamacion de los bronquios como bronquitis"},
            {"label": "DIAG", "pattern": "presenta celulitis por la afectacion primaraia del tejido celular subcutaneo con cierta afectacion de la dermis"},
            {"label": "DIAG", "pattern": "colico renal por obstruccion de la via urinaria"},
            {"label": "DIAG", "pattern": "presenta conjuntivitis por inflamacion intensa y repetitiva"},
            {"label": "DIAG", "pattern": "presenta efecto adverso de farmacos por los medicamentos ingeridos y automedicados"},
            {"label": "DIAG", "pattern": "coexistencia de fiebre y erupcion cutanea de caracteristicas inespecificas por exantema"},
            {"label": "DIAG", "pattern": "aumento del tamaño del sistema ventricular por hidrocefalia adquirida"},
            {"label": "DIAG", "pattern": "infeccion de VIH asintomatica por no presentar sintomas considerados con anterioridad al contagio"},
            {"label": "DIAG", "pattern": "presenta migraña por el sindrome doloroso caracterizado por la aparicion de accesos paroxisticos de cefalalgia"},
            {"label": "DIAG", "pattern": "presecncia de sintomas y signos de afectacion en los ojos por patologia ocular"},
            {"label": "DIAG", "pattern": "contusion de la pared toracia con lesiones intratoracias por contacto"},
            {"label": "DIAG", "pattern": "presenta patologia pulmonar de probable origen tuberculoso por TBC."},

            {"label": "ANTP", "pattern": "TBC"},
            {"label": "ANTP", "pattern": "Asma"},
            {"label": "ANTP", "pattern": "Trasferencia sanguinea"},
            {"label": "ANTP", "pattern": "Uso de medicinas"},
            {"label": "ANTP", "pattern": "Consumo de drogas"},
            {"label": "ANTP", "pattern": "Intervencion quirurgica"},
            {"label": "ANTP", "pattern": "Alergias"},
            {"label": "ANTP", "pattern": "Accidentes"},
            {"label": "ANTP", "pattern": "Trastornos psicologicos"},
            {"label": "ANTP", "pattern": "Hospitalizaciones"},

            {"label": "ANTF", "pattern": "Obesidad"},
            {"label": "ANTF", "pattern": "TBC"},
            {"label": "ANTF", "pattern": "VIH/Sida"},
            {"label": "ANTF", "pattern": "Hipertension arterial"},
            {"label": "ANTF", "pattern": "Diabetes Milittus tipo 1y 2"},
            {"label": "ANTF", "pattern": "Diabetes Milittus tipo 1 y 2"},
            {"label": "ANTF", "pattern": "Infartos"},
            {"label": "ANTF", "pattern": "Trastorno psicologicos"},
            {"label": "ANTF", "pattern": "Hiperlipidemia"},
            {"label": "ANTF", "pattern": "Drogas"},
            {"label": "ANTF", "pattern": "Violencia interfamiliar"},
            {"label": "ANTF", "pattern": "Maltratos"},
            {"label": "ANTF", "pattern": "Madre adolescente"},
            {"label": "ANTF", "pattern": "Convivencia familiar  - padre"},
            {"label": "ANTF", "pattern": "Convivencia familiar  - madre"},
            {"label": "ANTF", "pattern": "Convivencia familiar  - hijos"},
            {"label": "ANTF", "pattern": "Convivencia familiar  - pareja(s)"},
            {"label": "ANTF", "pattern": "Convivencia familiar  - hermanos"},
            {"label": "ANTF", "pattern": "Convivencia familiar  - otros"},

            {"label": "OBSR", "pattern": "Blopress 16 mg Caja por 30 Comprimidos"},
            {"label": "OBSR", "pattern": "Caditar Mio Caja por 50 Tabletas"},
            {"label": "OBSR", "pattern": "Cluvax Caja por 3 Cápsulas Blandas"},
            {"label": "OBSR", "pattern": "Dicetel 100 mg Caja por 14 Tabletas"},
            {"label": "OBSR", "pattern": "Femigen Forte Caja por 60 Tabletas"},
            {"label": "OBSR", "pattern": "Orfenadrina Citrato de 60 mg"},
            {"label": "OBSR", "pattern": "Claritromicina 500 mg Caja por 100 tabletas"},
            {"label": "OBSR", "pattern": "Acepot Suspensión Inyectable 1 mL"},
            {"label": "OBSR", "pattern": "Antalgina Jarabe 250 mg Caja con 60 mL"},
            {"label": "OBSR", "pattern": "Calmic Caja por 60 Cápsulas Blandas"},
            {"label": "OBSR", "pattern": "Cefuroxima 500 mg con 50 Tabletas"},
            {"label": "OBSR", "pattern": "Ciproflox 500 mg Caja por 10 Tabletas"}
        ]
